# Generated by Django 5.0.6 on 2024-06-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
