# Generated by Django 5.0.6 on 2024-06-02 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes_count',
        ),
        migrations.CreateModel(
            name='Movie_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(related_name='liked_movies', through='movie.Movie_Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.ManyToManyField(related_name='liked_review', through='movie.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
